exports.fileUpload = [
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Audit committee functioning",
            "Function": "Result",
            "DP Code": "AUDR001",
            "Indicator": "Total audit committee members",
            "Description": "Total audit committee members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR001",
            "Indicator": "Total board fixed cash based compensation",
            "Description": "Total fixed cash based compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR003",
            "Indicator": "Total board variable cash based compensation (bonuses and other cash incentive based pay)",
            "Description": "Total variable cash based compensation (bonuses and other cash incentive based pay) paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR005",
            "Indicator": "Total board other fringe compensation",
            "Description": "Total fringe compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR007",
            "Indicator": "Total board share based compensation",
            "Description": "Total share based compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR009",
            "Indicator": "Non-board related compensation for the board",
            "Description": "Non-board related compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR011",
            "Indicator": "Total Board compensation\r\n",
            "Description": "Total board compensation.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR001",
            "Indicator": "Total female board members",
            "Description": "Total number of Board members who are female or persons identifying as females. ",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR002",
            "Indicator": "Percentage of female board members",
            "Description": "Percentage of Board members who are female or persons identifying as females, at the end of the fiscal year.",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR003",
            "Indicator": "Total board members tagged as minority culture/nationality/ethnicity",
            "Description": "Total board members tagged as minority ethnicity/culture/nationality",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR004",
            "Indicator": "Percentage of board members tagged as minority ethnicity/culture/nationality",
            "Description": "Percentage of board members tagged as minority ethnicity/culture/nationality at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR001",
            "Indicator": "Total Independent board members",
            "Description": "Total number of independent board members.",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR002",
            "Indicator": "Percentage of independent board members",
            "Description": "Percentage of independent board members at the end of the fiscal year\r\n",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR003",
            "Indicator": "Total non executive board members",
            "Description": "Total non executive board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR004",
            "Indicator": "Percentage of non executive board members",
            "Description": "Percentage of non executive board members at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR005",
            "Indicator": "Total number of promoter board members",
            "Description": "Total number of promoter board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR006",
            "Indicator": "Percentage of promoter board members",
            "Description": "Percentage of promoter board members at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR007",
            "Indicator": "Total number of executive board members",
            "Description": "Total number of executive board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR008",
            "Indicator": "Percentage of executive board members",
            "Description": "Percentage of executive board members at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR009",
            "Indicator": "Number of active board members with non-executive role.",
            "Description": "Number of board members that serve other interests with the company other than being non-executive board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR010",
            "Indicator": "Percentage of active board members with non-executive role.",
            "Description": "Percentage of active board members serving other interests with the company other than being non-executive board members",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR011",
            "Indicator": "Total number of shares held by the board",
            "Description": "Total number of shares held by the board members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of shares",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR015",
            "Indicator": "Average term length in years of board members",
            "Description": "Average term length in years that the active members have been on the board as of the current fiscal year",
            "Data Type": "Number",
            "Unit": "Average term length in years",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR016",
            "Indicator": "Average Number of other mandates of board members\r\n",
            "Description": "Average number of other mandates/corporate affiliates held by board members at the end of the fiscal year\r\n",
            "Data Type": "Number",
            "Unit": "Number of mandates",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR001",
            "Indicator": "Total board members",
            "Description": "Total number of active board members at the end of the financial year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR002",
            "Indicator": "Total board members having financial expertise",
            "Description": "Total board members having financial expertise",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR003",
            "Indicator": "Percentage of board members having financial expertise",
            "Description": "Percentage of board members having financial expertise at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR004",
            "Indicator": "Total board members having industrial experience",
            "Description": "Total board members having industry experience",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR005",
            "Indicator": "Percentage of board members having industrial experience",
            "Description": "Percentage of board members having industry experience at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR006",
            "Indicator": "Average age of board members",
            "Description": "Average age of board members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Average age in years",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Committee Functioning",
            "Function": "Result",
            "DP Code": "COMR001",
            "Indicator": "Total remuneration committee members",
            "Description": "Total remuneration committee members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Committee Functioning",
            "Function": "Result",
            "DP Code": "COMR004",
            "Indicator": "Total nomination committee members",
            "Description": "Total nomination committee members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR013",
            "Indicator": "Total Key Management Personel fixed cash based compensation",
            "Description": "Total Key Management Personel's fixed cash based compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR015",
            "Indicator": "Total Key Management Personel variable cash based compensation (bonuses and other cash incentive based pay)",
            "Description": "Total Key Management Personel's variable cash based compensation (bonuses and other cash incentive based pay)",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR017",
            "Indicator": "Total Key Management Personel other fringe compensation",
            "Description": "Total Key Management Personel's other fringe compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR019",
            "Indicator": "Total Key Management Personel total share based compensation",
            "Description": "Total Key Management Personel's total share based compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR021",
            "Indicator": "Total Key Management Personnel  Compensation",
            "Description": "Total Key Management Personnel's  Compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR001",
            "Indicator": "Number of company shares held by all Key Management Personel",
            "Description": "Number of company shares held by Key Management Personnel",
            "Data Type": "Number",
            "Unit": "Number of shares",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR003",
            "Indicator": "Size of Key Management Personel",
            "Description": "Size of Key Management Personel",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR004",
            "Indicator": "Total number of females forming part of the Key Management Personel",
            "Description": "Total number of women or persons identifying as women, forming part of the Key Management Personnel.",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2019-2020",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR005",
            "Indicator": "Percentage of females forming part of the Key Management Personel",
            "Description": "Percentage of women or persons identifying as women, forming part of the key management personnel at the end of the fiscal year under evaluation.",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR006",
            "Indicator": "Average age of the Key Management Personel",
            "Description": "Average age of the Key Management Personel",
            "Data Type": "Number",
            "Unit": "Average age in years",
            "Fiscal Year": "2019-2020"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Audit committee functioning",
            "Function": "Result",
            "DP Code": "AUDR001",
            "Indicator": "Total audit committee members",
            "Description": "Total audit committee members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR001",
            "Indicator": "Total board fixed cash based compensation",
            "Description": "Total fixed cash based compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR003",
            "Indicator": "Total board variable cash based compensation (bonuses and other cash incentive based pay)",
            "Description": "Total variable cash based compensation (bonuses and other cash incentive based pay) paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR005",
            "Indicator": "Total board other fringe compensation",
            "Description": "Total fringe compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR007",
            "Indicator": "Total board share based compensation",
            "Description": "Total share based compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR009",
            "Indicator": "Non-board related compensation for the board",
            "Description": "Non-board related compensation paid to the directors.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board compensation",
            "Function": "Result",
            "DP Code": "BOCR011",
            "Indicator": "Total Board compensation\r\n",
            "Description": "Total board compensation.",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR001",
            "Indicator": "Total female board members",
            "Description": "Total number of Board members who are female or persons identifying as females. ",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR002",
            "Indicator": "Percentage of female board members",
            "Description": "Percentage of Board members who are female or persons identifying as females, at the end of the fiscal year.",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR003",
            "Indicator": "Total board members tagged as minority culture/nationality/ethnicity",
            "Description": "Total board members tagged as minority ethnicity/culture/nationality",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board diversity",
            "Function": "Result",
            "DP Code": "BODR004",
            "Indicator": "Percentage of board members tagged as minority ethnicity/culture/nationality",
            "Description": "Percentage of board members tagged as minority ethnicity/culture/nationality at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR001",
            "Indicator": "Total Independent board members",
            "Description": "Total number of independent board members.",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR002",
            "Indicator": "Percentage of independent board members",
            "Description": "Percentage of independent board members at the end of the fiscal year\r\n",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR003",
            "Indicator": "Total non executive board members",
            "Description": "Total non executive board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR004",
            "Indicator": "Percentage of non executive board members",
            "Description": "Percentage of non executive board members at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR005",
            "Indicator": "Total number of promoter board members",
            "Description": "Total number of promoter board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR006",
            "Indicator": "Percentage of promoter board members",
            "Description": "Percentage of promoter board members at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR007",
            "Indicator": "Total number of executive board members",
            "Description": "Total number of executive board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR008",
            "Indicator": "Percentage of executive board members",
            "Description": "Percentage of executive board members at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR009",
            "Indicator": "Number of active board members with non-executive role.",
            "Description": "Number of board members that serve other interests with the company other than being non-executive board members",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR010",
            "Indicator": "Percentage of active board members with non-executive role.",
            "Description": "Percentage of active board members serving other interests with the company other than being non-executive board members",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR011",
            "Indicator": "Total number of shares held by the board",
            "Description": "Total number of shares held by the board members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of shares",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR015",
            "Indicator": "Average term length in years of board members",
            "Description": "Average term length in years that the active members have been on the board as of the current fiscal year",
            "Data Type": "Number",
            "Unit": "Average term length in years",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board independence",
            "Function": "Result",
            "DP Code": "BOIR016",
            "Indicator": "Average Number of other mandates of board members\r\n",
            "Description": "Average number of other mandates/corporate affiliates held by board members at the end of the fiscal year\r\n",
            "Data Type": "Number",
            "Unit": "Number of mandates",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR001",
            "Indicator": "Total board members",
            "Description": "Total number of active board members at the end of the financial year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR002",
            "Indicator": "Total board members having financial expertise",
            "Description": "Total board members having financial expertise",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR003",
            "Indicator": "Percentage of board members having financial expertise",
            "Description": "Percentage of board members having financial expertise at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR004",
            "Indicator": "Total board members having industrial experience",
            "Description": "Total board members having industry experience",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR005",
            "Indicator": "Percentage of board members having industrial experience",
            "Description": "Percentage of board members having industry experience at the end of the fiscal year",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Board structure and functioning",
            "Function": "Result",
            "DP Code": "BOSR006",
            "Indicator": "Average age of board members",
            "Description": "Average age of board members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Average age in years",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Committee Functioning",
            "Function": "Result",
            "DP Code": "COMR001",
            "Indicator": "Total remuneration committee members",
            "Description": "Total remuneration committee members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Board & Committee functioning",
            "Key Issues": "Committee Functioning",
            "Function": "Result",
            "DP Code": "COMR004",
            "Indicator": "Total nomination committee members",
            "Description": "Total nomination committee members at the end of the fiscal year",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR013",
            "Indicator": "Total Key Management Personel fixed cash based compensation",
            "Description": "Total Key Management Personel's fixed cash based compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR015",
            "Indicator": "Total Key Management Personel variable cash based compensation (bonuses and other cash incentive based pay)",
            "Description": "Total Key Management Personel's variable cash based compensation (bonuses and other cash incentive based pay)",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR017",
            "Indicator": "Total Key Management Personel other fringe compensation",
            "Description": "Total Key Management Personel's other fringe compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR019",
            "Indicator": "Total Key Management Personel total share based compensation",
            "Description": "Total Key Management Personel's total share based compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management compensation",
            "Function": "Result",
            "DP Code": "MACR021",
            "Indicator": "Total Key Management Personnel  Compensation",
            "Description": "Total Key Management Personnel's  Compensation",
            "Data Type": "Number",
            "Unit": "Compensation in INR",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR001",
            "Indicator": "Number of company shares held by all Key Management Personel",
            "Description": "Number of company shares held by Key Management Personnel",
            "Data Type": "Number",
            "Unit": "Number of shares",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR003",
            "Indicator": "Size of Key Management Personel",
            "Description": "Size of Key Management Personel",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR004",
            "Indicator": "Total number of females forming part of the Key Management Personel",
            "Description": "Total number of women or persons identifying as women, forming part of the Key Management Personnel.",
            "Data Type": "Number",
            "Unit": "Number of members",
            "Fiscal Year": "2018-2019",
            "Response": "0"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR005",
            "Indicator": "Percentage of females forming part of the Key Management Personel",
            "Description": "Percentage of women or persons identifying as women, forming part of the key management personnel at the end of the fiscal year under evaluation.",
            "Data Type": "Percentage",
            "Unit": "Percentage of members",
            "Fiscal Year": "2018-2019"
        },
        {
            "Category": "Corporate Governance",
            "Theme": "Management Structure and Compensation",
            "Key Issues": "Management structure",
            "Function": "Result",
            "DP Code": "MASR006",
            "Indicator": "Average age of the Key Management Personel",
            "Description": "Average age of the Key Management Personel",
            "Data Type": "Number",
            "Unit": "Average age in years",
            "Fiscal Year": "2018-2019"
        }
    ]
    
